name: Build and deploy web app
on: [push]
jobs:
    build:
        name: Build React app
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

            - name: Setup Pnpm
              uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6

            - name: Setup Node.js
              uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
              with:
                  node-version: 24
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build React app
              run: pnpm run build
              env:
                  PUBLIC_URL: https://pass.yellowlake.net

            - name: Save build output
              uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
              with:
                  name: app-dist
                  path: dist
    deploy:
        name: Deploy static app to S3
        if: github.ref == 'refs/heads/main'
        needs: build
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

            - name: Restore build output
              uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
              with:
                  name: app-dist
                  path: dist

            - name: Configure AWS
              uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: eu-central-1

            - name: Upload to AWS S3
              run: aws s3 sync dist s3://pass.wayspace.net --delete
